/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore;

import io.apimatic.core.GlobalConfiguration;
import io.apimatic.core.authentication.HeaderAuth;
import io.apimatic.coreinterfaces.http.request.ArraySerializationFormat;
import io.swagger.petstore.models.OAuthScopeEnum;
import io.swagger.petstore.models.OAuthToken;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/**
 * Utility class for OAuth 2 authorization and token management.
 */
public class ImplicitAuthManager extends HeaderAuth implements ImplicitAuth {

    /**
     * Private instance of the configuration to be used.
     */
    private GlobalConfiguration config;

    private String oAuthClientId;

    private String oAuthRedirectUri;

    private OAuthToken oAuthToken;

    private List<OAuthScopeEnum> oAuthScopes;

    /**
     * Constructor.
     */
    public ImplicitAuthManager(String oAuthClientId, String oAuthRedirectUri, OAuthToken oAuthToken,
            List<OAuthScopeEnum> oAuthScopes) {
        super(Collections.singletonMap("Authorization",
                getAuthorizationHeader(oAuthToken)));
        this.oAuthClientId = oAuthClientId;
        this.oAuthRedirectUri = oAuthRedirectUri;
        this.oAuthToken = oAuthToken;
        this.oAuthScopes = oAuthScopes;
    }

    /**
    * Apply GlobalConfiguration for token management.
    * @param config GlobalConfiguration instance
    */
    protected void applyGlobalConfiguration(GlobalConfiguration config) {
        this.config = config;
    }


    /**
     * String value for oAuthClientId.
     * @return oAuthClientId
     */
    public String getOAuthClientId() {
        return oAuthClientId;
    }

    /**
     * String value for oAuthRedirectUri.
     * @return oAuthRedirectUri
     */
    public String getOAuthRedirectUri() {
        return oAuthRedirectUri;
    }

    /**
     * OAuthToken value for oAuthToken.
     * @return oAuthToken
     */
    public OAuthToken getOAuthToken() {
        return oAuthToken;
    }

    /**
     * List of OAuthScopeEnum value for oAuthScopes.
     * @return oAuthScopes
     */
    public List<OAuthScopeEnum> getOAuthScopes() {
        return oAuthScopes;
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param oAuthClientId String value for credentials.
     * @param oAuthRedirectUri String value for credentials.
     * @param oAuthToken OAuthToken value for credentials.
     * @param oAuthScopes List of OAuthScopeEnum value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String oAuthClientId, String oAuthRedirectUri, OAuthToken oAuthToken,
            List<OAuthScopeEnum> oAuthScopes) {
        return oAuthClientId.equals(getOAuthClientId())
                && oAuthRedirectUri.equals(getOAuthRedirectUri())
                && ((getOAuthToken() == null && oAuthToken == null)
                        || (getOAuthToken() != null && oAuthToken != null
                                && oAuthToken.toString().equals(getOAuthToken().toString())))
                && ((getOAuthScopes() == null && oAuthScopes == null)
                        || (getOAuthScopes() != null && oAuthScopes != null
                                && oAuthScopes.equals(getOAuthScopes())));
    }

    /**
     * Converts this ImplicitAuthManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ImplicitAuthManager [" + "oAuthClientId=" + oAuthClientId + ", oAuthRedirectUri="
                + oAuthRedirectUri + ", oAuthToken=" + oAuthToken + ", oAuthScopes=" + oAuthScopes
                + "]";
    }

    /**
     * Build an authorization URL for taking the user's consent to access data.
     * @param state An opaque state string
     * @param additionalParameters Additional parameters to add the the authorization URL
     * @return Authorization URL
     */
    public String buildAuthorizationUrl(final String state,
            final Map<String, String> additionalParameters) {

        // the uri for api requests
        StringBuilder queryBuilder = new StringBuilder(config.getBaseUri().apply(Server.AUTH_SERVER.value()));
        queryBuilder.append("/authorize");

        // build query params
        Map<String, Object> queryParameters = new HashMap<String, Object>() {
            private static final long serialVersionUID = 1L;
            {
                put("response_type", "token");
                put("client_id", oAuthClientId);
                put("redirect_uri", oAuthRedirectUri);
                put("scope", stringJoin(oAuthScopes, " "));
                put("state", state);
            }
        };

        // process optional query parameters
        if (additionalParameters != null) {
            queryParameters.putAll(additionalParameters);
        }

        ApiHelper.appendUrlWithQueryParameters(queryBuilder, queryParameters, ArraySerializationFormat.INDEXED);

        // validate and preprocess url
        return ApiHelper.cleanUrl(queryBuilder);
    }
    
    /**
     * Build an authorization URL for taking the user's consent to access data.
     * @return Authorization URL
     */
    public String buildAuthorizationUrl() {
        return buildAuthorizationUrl(null, null);
    }

    /**
     * Build an authorization URL for taking the user's consent to access data.
     * @param state An opaque state string
     * @return Authorization URL
     */
    public String buildAuthorizationUrl(final String state) {
        return buildAuthorizationUrl(state, null);
    }

    /**
     * Join string collection elements using delimiter.
     * @param col String collection to join
     * @param delim Delimiter
     * @return String joined by delimiter
     */
    private String stringJoin(Collection<?> col, String delim) {
        if (col == null) {
            return null;
        }
        StringBuilder sb = new StringBuilder();
        Iterator<?> iter = col.iterator();
        if (iter.hasNext()) {
            sb.append(iter.next().toString());
        }
        while (iter.hasNext()) {
            sb.append(delim);
            sb.append(iter.next().toString());
        }
        return sb.toString();
    }

    /**
     * Has the OAuth token expired?.
     * @return True if expired
     */
    public boolean isTokenExpired() {
        if (getOAuthToken() == null) { 
            throw new IllegalStateException("OAuth token is missing.");
        }

        return getOAuthToken().getExpiry() != null 
            && getOAuthToken().getExpiry() < (System.currentTimeMillis() / 1000L); 
    }

    /**
    * Create authorization header for API calls.
    * @param token OAuth token
    * @return Authorization header
    */
    private static String getAuthorizationHeader(OAuthToken token) {
        if (token == null) {
            return null;
        }
        return "Bearer " + token.getAccessToken();
    }

    /**
    * Validate the authentication on the httpRequest
    */
    @Override
    public void validate() {
        if (getOAuthToken() == null) {
            throw new IllegalStateException(
                "Client is not authorized.An OAuth token is needed to make API calls.");
        }

        if (isTokenExpired()) {
            throw new IllegalStateException(
                "OAuth token is expired. A valid token is needed to make API calls.");
        }
     }

}
